### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method '<' was called on null

### ISSUE THREAD

**Issue by DmitryVoronko** [Renesanse/worker_manager#22]
### 3.2.7 version in pub.dev is broken and not consistent with master

I'm trying to run an application but receive an exception:

```bash
E/flutter ( 9315): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method '<' was called on null.
E/flutter ( 9315): Receiver: null
E/flutter ( 9315): Tried calling: <(8)
E/flutter ( 9315): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter ( 9315): #1      _Executor.warmUp (package:worker_manager/src/executor.dart:60:23)
E/flutter ( 9315): #2      main (package:tc_x/main.dart:12:20)
E/flutter ( 9315): #3      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter ( 9315): #4      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 9315): #5      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 9315): #6      _runZoned (dart:async/zone.dart:1630:10)
E/flutter ( 9315): #7      runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter ( 9315): #8      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter ( 9315): #9      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 9315): #10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 9315): 
```

3.2.7 sources:

```dart
55  @override
56  Future<void> warmUp({bool log = false, int isolatesCount}) async {
57    _log = log;
58    final processors = numberOfProcessors;
59    var processorsNumber =
60        isolatesCount < processors ? isolatesCount : processors;
61    if (processorsNumber == 1) processorsNumber = 2;
62    for (var i = 0; i < processorsNumber - 1; i++) {
63      _pool.add(IsolateWrapper());
64    }
65    logInfo('${_pool.length} has been spawned');
66    await Future.wait(_pool.map((iw) => iw.initialize()));
67    logInfo('initialized');
68  }
```

As you can see in line 60 you are trying to compare nullable `isolatesCount` with `processors`. But `isolatesCount` is `null` and `null` doesn't have `<` operator.

I wanted to resolve this issue by myself, but I found that sources in pub.dev and master are not consistent

**Comment by Renesanse** [comment]
Hello @DmitryVoronko thx for creating the issue, bug already resolved in 3.2.8
