### ISSUE TITLE
Undetermined Nullability on flutter web when import worker_manager

### ISSUE THREAD

**Issue by basketball-ico** [Renesanse/worker_manager#34]
```dart
import 'package:flutter/material.dart';

import 'package:worker_manager/worker_manager.dart';

void main() {
  runApp(Container());
}

```

```shell
[✓] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19042.985], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio
[√] VS Code, 64-bit edition (version 1.56.2)
[√] Connected device (2 available)
```

```dart
Launching lib\main.dart on Chrome in debug mode...
lib\main.dart:1
Unhandled exception:
Unsupported operation: Undetermined Nullability
#0      ProgramCompiler._emitFutureOrType (package:dev_compiler/src/kernel/compiler.dart:2894:7)
#1      ProgramCompiler._normalizeFutureOr (package:dev_compiler/src/kernel/compiler.dart:2763:12)

#2      ProgramCompiler.visitFutureOrType (package:dev_compiler/src/kernel/compiler.dart:2776:7)
#3      FutureOrType.accept (package:kernel/ast.dart:11126:42)

#4      ProgramCompiler._emitType (package:dev_compiler/src/kernel/compiler.dart:2692:54)
#5      ProgramCompiler._emitArgumentList (package:dev_compiler/src/kernel/compiler.dart:5404:41)
#6      ProgramCompiler._emitMethodCall (package:dev_compiler/src/kernel/compiler.dart:4721:16)

#7      ProgramCompiler.visitInstanceInvocation (package:dev_compiler/src/kernel/compiler.dart:4641:12)
#8      InstanceInvocation.accept (package:kernel/ast.dart:5178:44)
#9      ProgramCompiler._visitExpression (package:dev_compiler/src/kernel/compiler.dart:3705:20)

#10     ProgramCompiler.visitExpressionStatement (package:dev_compiler/src/kernel/compiler.dart:3786:12)
#11     ExpressionStatement.accept (package:kernel/ast.dart:8462:43)

#12     ProgramCompiler._visitStatement (package:dev_compiler/src/kernel/compiler.dart:3611:20)
#13     MappedListIterable.elementAt (dart:_internal/iterable.dart:412:31)

#14     ListIterator.moveNext (dart:_internal/iterable.dart:341:26)
#15     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
#16     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)

#17     new List.of (dart:core-patch/array_patch.dart:50:28)
#18     ListIterable.toList (dart:_internal/iterable.dart:212:44)


```

**Comment by luiz-simples** [comment]
me too

**Comment by Renesanse** [comment]
I guess it is flutter's bug, closing for now
