### ISSUE TITLE
Exception in flutter web - LateInitializationError: Field sendPort has not been initialized

### ISSUE THREAD

**Issue by srix55** [Renesanse/worker_manager#65]
Running the example app throws exceptions in flutter web. And, it looks like tasks get queued up, never executed.

https://user-images.githubusercontent.com/6329365/180234633-762a9d6f-a132-4801-bb20-9bc3f59e64e2.mp4
```
Error: LateInitializationError: Field 'sendPort' has not been initialized.
    at Object.throw_ [as throw] (http://localhost:40607/dart_sdk.js:5080:11)
    at get sendPort [as sendPort] (http://localhost:40607/packages/worker_manager/src/worker/worker_web.dart.lib.js:309:39)
    at Runnable.new.call (http://localhost:40607/packages/worker_manager/src/worker/worker_web.dart.lib.js:338:34)
    at WorkerImpl._execute (http://localhost:40607/packages/worker_manager/src/worker/worker_web.dart.lib.js:148:23)
    at worker_web.WorkerImpl.new.work (http://localhost:40607/packages/worker_manager/src/worker/worker_web.dart.lib.js:142:71)
    at work.next (<anonymous>)
    at runBody (http://localhost:40607/dart_sdk.js:40660:34)
    at Object._async [as async] (http://localhost:40607/dart_sdk.js:40691:7)
    at worker_web.WorkerImpl.new.work (http://localhost:40607/packages/worker_manager/src/worker/worker_web.dart.lib.js:136:20)
    at [_schedule] (http://localhost:40607/packages/worker_manager/src/worker/worker_web.dart.lib.js:915:28)
    at executing (http://localhost:40607/packages/worker_manager/src/worker/worker_web.dart.lib.js:884:26)
    at worker_manager._Executor._internal.execute (http://localhost:40607/packages/worker_manager/src/worker/worker_web.dart.lib.js:898:16)
    at http://localhost:40607/packages/example/main.dart.lib.js:508:55
    at main._MyHomePageState.new.setState (http://localhost:40607/packages/flutter/src/widgets/title.dart.lib.js:11584:22)
    at http://localhost:40607/packages/example/main.dart.lib.js:506:28
    at tap.TapGestureRecognizer.new.invokeCallback (http://localhost:40607/packages/flutter/src/gestures/recognizer.dart.lib.js:198:18)
    at tap.TapGestureRecognizer.new.handleTapUp (http://localhost:40607/packages/flutter/src/gestures/tap.dart.lib.js:411:42)
    at [_checkUp] (http://localhost:40607/packages/flutter/src/gestures/tap.dart.lib.js:217:12)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (http://localhost:40607/packages/flutter/src/gestures/tap.dart.lib.js:166:23)
    at tap.TapGestureRecognizer.new.handleEvent (http://localhost:40607/packages/flutter/src/gestures/recognizer.dart.lib.js:444:16)
    at [_dispatch] (http://localhost:40607/packages/flutter/src/gestures/pointer_router.dart.lib.js:86:9)
    at http://localhost:40607/packages/flutter/src/gestures/pointer_router.dart.lib.js:112:26
    at LinkedMap.new.forEach (http://localhost:40607/dart_sdk.js:27745:11)
    at [_dispatchEventToRoutes] (http://localhost:40607/packages/flutter/src/gestures/pointer_router.dart.lib.js:110:29)
    at pointer_router.PointerRouter.new.route (http://localhost:40607/packages/flutter/src/gestures/pointer_router.dart.lib.js:105:37)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (http://localhost:40607/packages/flutter/src/gestures/binding.dart.lib.js:367:26)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:40607/packages/flutter/src/gestures/binding.dart.lib.js:355:24)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (http://localhost:40607/packages/flutter/src/rendering/layer.dart.lib.js:5440:13)
    at [_handlePointerEventImmediately] (http://localhost:40607/packages/flutter/src/gestures/binding.dart.lib.js:331:14)
    at binding$5.WidgetsFlutterBinding.new.handlePointerEvent (http://localhost:40607/packages/flutter/src/gestures/binding.dart.lib.js:305:43)
    at [_flushPointerEventQueue] (http://localhost:40607/packages/flutter/src/gestures/binding.dart.lib.js:295:14)
    at [_handlePointerDataPacket] (http://localhost:40607/packages/flutter/src/gestures/binding.dart.lib.js:286:54)
    at Object.invoke1 (http://localhost:40607/dart_sdk.js:191747:7)
    at _engine.EnginePlatformDispatcher.__.invokeOnPointerDataPacket (http://localhost:40607/dart_sdk.js:171943:15)
    at [_onPointerData] (http://localhost:40607/dart_sdk.js:172879:49)
    at http://localhost:40607/dart_sdk.js:173317:28
    at http://localhost:40607/dart_sdk.js:173273:16
    at loggedHandler (http://localhost:40607/dart_sdk.js:172978:11)
```

**Comment by srix55** [comment]
Since sendPorts are redundant for web, I circumvented the issue by assigning a dummy sendPort. PR raised

https://user-images.githubusercontent.com/6329365/180240191-02a6133e-8e92-461b-a931-70fd8b669663.mp4

.

**Comment by Samuel-ML** [comment]
I have the next error when i try in flutter web
https://user-images.githubusercontent.com/117123908/202292552-94ef6c8a-eb34-42f7-9380-f11317596b12.mov

**Comment by Renesanse** [comment]
> I have the next error when i try in flutter web
> https://user-images.githubusercontent.com/117123908/202292552-94ef6c8a-eb34-42f7-9380-f11317596b12.mov

resolved in 890759e1c2f153e1aab38322c8e9b525c36ce324, pub.dev also updated to 4.4.8. Thx.

**Comment by aytunch** [comment]
Hi @Renesanse,
In pub dev web is not shown as a supported platform. Is this the case? What is the official status on web support?
I see devs getting success using `worker_manager` in web. Is this at your own risk? Or is a hack necessary to make it work?

**Comment by daniilpicnic** [comment]
> 
Newest version of worker_manager should work on Flutter web, I you have a problems with worker_manager pls open new issue. What success do you mean? Worker_manager web implementation is the same as compute method from Flutter foundation and it is just a async method in main event loop.

**Comment by Renesanse** [comment]
> Hi @Renesanse,
> In pub dev web is not shown as a supported platform. Is this the case? What is the official status on web support?
> I see devs getting success using `worker_manager` in web. Is this at your own risk? Or is a hack necessary to make it work?

641791
