### ISSUE TITLE
Plugins throw "Binding has not yet been initialized" exception in isolates

### ISSUE THREAD

**Issue by srix55** [Renesanse/worker_manager#72]
I am trying to get path_provider to work in the isolate for getting the application support directory path.
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Binding has not yet been initialized.
The "instance" getter on the ServicesBinding binding mixin is only available once that binding has been initialized.
Typically, this is done by calling "WidgetsFlutterBinding.ensureInitialized()" or "runApp()" (the latter calls the former). Typically this call is done in the "void main()" method. The "ensureInitialized" method is idempotent; calling it multiple times is not harmful. After calling that method, the "instance" getter will return the binding.
In a test, one can call "TestWidgetsFlutterBinding.ensureInitialized()" as the first line in the test's "main()" method to initialize the binding.
If ServicesBinding is a custom binding mixin, there must also be a custom binding class, like WidgetsFlutterBinding, but that mixes in the selected binding, and that is the class that must be constructed before using the "instance" getter.
#0      BindingBase.checkInstance.<anonymous closure> (package:flutter/src/foundation/binding.dart:284:9)
#1      BindingBase.checkInstance (package:flutter/src/foundation/binding.dart:366:6)
#2      ServicesBinding.instance (package:flutter/src/services/binding.dart:54:54)
#3      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:254:45)
#4      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:289:15)
#5      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:472:12)
#6      MethodChannelPathProvider.getApplicationSupportPath (package:path_provider_platform_interface/src/method_channel_path_provider.dart:37:26)
#7      getApplicationSupportDirectory (package:path_provider/path_provider.dart:77:40)
#8      hello (package:example/main.dart:125:25)
#9      Runnable.call (package:worker_manager/src/scheduling/runnable.dart:46:18)
#10     WorkerImpl._execute (package:worker_manager/src/worker/worker_io.dart:65:49)
#11     WorkerImpl._anotherIsolate.<anonymous closure> (package:worker_manager/src/worker/worker_io.dart:76:38)
#12     _RootZone.runUnaryGuarded (dart:async/zone.dart:1586:10)
#13     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#14     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#15     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:774:19)
#16     _StreamController._add (dart:async/stream_controller.dart:648:7)
#17     _StreamController.add (dart:async/stream_controller.dart:596:5)
#18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by srix55** [comment]
Looks like plugins don't work in isolates. So, we will have to use ports to get plugin data through from main isolate.

**Comment by srix55** [comment]
I don't think there's much we can do about it except to send required info during isolate spawn. So, closing this issue for now.
